apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: filebeat-ds-${BUILD_VERSION}
spec:
  selector:
    app: filebeat-${BUILD_VERSION}
  template:
    metadata:
      name: filebeat
      labels:
        app: filebeat-${BUILD_VERSION}
    spec:
      containers:
      - name: filebeat
        image: 127.0.0.1:5000/filebeat:runtime-${BUILD_VERSION}
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      restartPolicy: Always
